on:
  push:
    branches:
      - main

name: Build Go Binary with Secrets

jobs:
  build:
    name: Build Go Binary with Embedded Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Parse secrets and build Go Binary
        run: |
          # Extraer valores desde los secretos
          DATABASE_URL_CLIENTE="${{ secrets.DATABASE_URL_CLIENTE1 }}"
          OTHER_VAR="static_value_or_other_secret"

          # Mostrar valores (opcional para debugging, oculta en ejecución real)
          echo "Compilando con DATABASE_URL_CLIENTE=${DATABASE_URL_CLIENTE}"

          # Compilar el binario con las variables incrustadas
          GOOS=windows GOARCH=amd64 go build \
            -ldflags="-X 'main.DatabaseURL=${DATABASE_URL_CLIENTE}' -X 'main.OtherVar=${OTHER_VAR}'" \
            -o myapp.exe ./main.go

      - name: Upload Go Binary to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: go-binary-windows
          path: myapp.exe