on:
  push:
    branches:
      - main

name: build-go-binary

jobs:
  build:
    name: Build Go Binary with Environment Variables
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment
        env:
          DATABASE_URL_CLIENTE1: ${{ secrets.DATABASE_URL_CLIENTE1 }}
        run: |
          echo "DATABASE_URL_CLIENTE1=${DATABASE_URL_CLIENTE1}" > .env

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.0'

      - name: Build Go Binary for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o myapp.exe ./main.go

      - name: Upload Go Binary to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: go-binary-windows
          path: myapp.exe